Add additional parameters to Camera and support xiTypeInteger64
Ximea-GmbH/xiapi pull request #15
Opened 2024-02-01 03:24 UTC by lgarbarini

Adds some additional parameters, one, `Timestamp` requires `u64` type, so also add support for that

2024-02-01 11:00 UTC, superbort requested changes
I suggested some changes, mostly to prevent the shortcomings of the C API to translate directly to Rust. We can do better than that.

2024-02-01 11:00 UTC, superbort commented on src/camera.rs
> +        mut debug_level: XI_DEBUG_LEVEL::Type;
```suggestion
/// Removed
```
I would not add this parameter to the camera and here is why:

You can already set the debug level using the static top level xiapi::set_debug_level function. The debug level in xiAPI is always global, so it does not make sense to have it on the camera. The static function has the additional advantage that you can use it before even openining a camera, so you can get debug output from the beginning.

2024-02-01 11:00 UTC, superbort commented on src/camera.rs
> +        mut acq_buffer_size: i32;
```suggestion
        /// Removed
```
I agree that this functionality is missing, but unfortunately just adding the parameter is not a good solution. ACQ_BUFFER_SIZE is a 32-bit signed integer in the C API. The highest possible value would only get us to 2GB, which may be too small in a real-world application.
In the C API this is solved by introducing an additional parameter ACQ_BUFFER_SIZE_UNIT and if you really want to use this directly in Rust, you can do so using xiapi_sys. For these higher level bindings however I would suggest wrapping both of these parameters in a nicer function that also catches some of the potential errors (e.g. negative parameter values). 
I will deal with this in a separate ticket.

2024-02-01 11:00 UTC, superbort commented on src/camera.rs
> +        mut transport_data_target: XI_TRANSPORT_DATA_TARGET_MODE::Type;
Did you test this with any other target? Using the GPU may require some additional changes, but this is a good start.

2024-02-01 11:13 UTC, superbort commented on src/camera.rs
> +        mut acq_buffer_size: i32;
#16 created for this.

2024-02-12 06:10 UTC, lgarbarini commented on src/camera.rs
> +        mut debug_level: XI_DEBUG_LEVEL::Type;
Wow, somehow I missed `set_debug_level`! Updated

2024-02-12 06:11 UTC, lgarbarini commented on src/camera.rs
> +        mut transport_data_target: XI_TRANSPORT_DATA_TARGET_MODE::Type;
I have tested this with both `UNIFIED` and `ZEROCOPY` and it seems to just work. I don't have the proper setup to test GPU Direct

2024-02-13 09:42 UTC, superbort approved these changes

2024-02-13 09:42 UTC, merged