Added some missing parameters to camera.
Ximea-GmbH/xiapi pull request #8
Opened 2023-11-08 13:25 UTC by GuillaumeSchmid

* auto_wb
* wb_kr
* wb_kg
* wb_kb

2023-11-13 15:36 UTC, superbort commented
This looks good to me and I will merge it as soon as I am able to run the tests with a camera connected. This may however still take a few days, since I don't have physical access to the cameras at the moment. Thank you for your contributions!

2023-11-29 11:43 UTC, superbort requested changes
Can you adjust the types for the simple on/off switches? They are represented as i32 on the lower level, but they will only ever be 0 or 1, so they can be XI_SWITCH in the high level bindings.
There should also be a more appropriate type for the buffer policy, but it is missing in the xiapi_sys bindings, so i32 is okay for now.

2023-11-29 11:43 UTC, superbort commented on src/camera.rs
> +        mut auto_wb: i32;
```suggestion
        mut auto_wb: XI_SWITCH::Type;
```
The parameter is a simple on/off switch, so it should have the appropriate type for that.

2023-11-29 11:43 UTC, superbort commented on src/camera.rs
> +        mut recent_frame: u32;
```suggestion
        mut recent_frame: XI_SWITCH::Type;
```
Same as above.

2023-11-29 12:00 UTC, GuillaumeSchmid commented
I made the changes you requested.

2023-11-29 14:38 UTC, merged